# Generated by Django 5.2.9 on 2025-12-08 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartaocredito',
            name='cor',
            field=models.CharField(choices=[('#820AD1', 'Roxo (Nubank)'), ('#FF8700', 'Laranja (Itaú)'), ('#CC092F', 'Vermelho (Bradesco/Santander)'), ('#FFD700', 'Dourado/Amarelo (Inter)'), ('#005CAA', 'Azul (Caixa/Azul)'), ('#000000', 'Preto (Black/C6)'), ('#28a745', 'Verde (Padrão)'), ('#6c757d', 'Cinza (Outros)')], default='#28a745', max_length=7),
        ),
    ]
