# Generated by Django 5.2.9 on 2025-12-09 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_categoria_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='compracartao',
            name='is_parcelado',
            field=models.BooleanField(default=False, verbose_name='É parcelado?'),
        ),
        migrations.AddField(
            model_name='compracartao',
            name='is_terceiro',
            field=models.BooleanField(default=False, verbose_name='É compra de terceiro?'),
        ),
        migrations.AddField(
            model_name='compracartao',
            name='nome_terceiro',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome do Terceiro'),
        ),
        migrations.AddField(
            model_name='compracartao',
            name='qtd_parcelas',
            field=models.IntegerField(default=1, verbose_name='Qtd Parcelas'),
        ),
    ]
