# Generated by Django 5.2.9 on 2026-01-09 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_compracartao_nome_terceiro_terceiro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartaocredito',
            name='dia_vencimento',
            field=models.IntegerField(default=1, verbose_name='Dia do Vencimento'),
        ),
        migrations.AlterField(
            model_name='cartaocredito',
            name='cor',
            field=models.CharField(choices=[('#820AD1', 'Roxo (Nubank)'), ('#FF8700', 'Laranja (Inter/Itaú)'), ('#CC092F', 'Vermelho (Bradesco/Santander)'), ('#FFD700', 'Dourado/Amarelo'), ('#005CAA', 'Azul (Caixa/Azul)'), ('#000000', 'Preto (Black/C6)'), ('#28a745', 'Verde (Padrão)'), ('#6c757d', 'Cinza (Outros)')], default='#28a745', max_length=7),
        ),
    ]
