# Generated by Django 5.2.9 on 2026-01-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cartaocredito_dia_vencimento_alter_cartaocredito_cor'),
    ]

    operations = [
        migrations.AddField(
            model_name='compracartao',
            name='pago',
            field=models.BooleanField(default=False, verbose_name='Conferido?'),
        ),
        migrations.AddField(
            model_name='transacao',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Pagamento'),
        ),
        migrations.AddField(
            model_name='transacao',
            name='pago',
            field=models.BooleanField(default=True, verbose_name='Pago?'),
        ),
    ]
