# Generated by Django 5.2.9 on 2026-01-11 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_metamensal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='metamensal',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='metamensal',
            name='tipo',
            field=models.CharField(choices=[('C', 'Por Categoria'), ('K', 'Total Cartões de Crédito'), ('E', 'Economia (Saldo Final)')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='metamensal',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.categoria'),
        ),
        migrations.AlterField(
            model_name='metamensal',
            name='valor_limite',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Meta'),
        ),
        migrations.AlterUniqueTogether(
            name='metamensal',
            unique_together={('usuario', 'tipo', 'categoria')},
        ),
    ]
