# Generated by Django 5.2.9 on 2026-01-11 15:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_metamensal_unique_together_metamensal_tipo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='metamensal',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='metamensal',
            name='periodo',
            field=models.CharField(choices=[('M', 'Mensal (Mês Atual)'), ('A', 'Anual (Ano Atual)')], default='M', max_length=1, verbose_name='Período'),
        ),
        migrations.AlterField(
            model_name='metamensal',
            name='tipo',
            field=models.CharField(choices=[('C', 'Por Categoria'), ('K', 'Total Cartões de Crédito'), ('E', 'Economia (Guardar)'), ('G', 'Orçamento Global (Teto de Gastos)')], default='C', max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='metamensal',
            unique_together={('usuario', 'tipo', 'categoria', 'periodo')},
        ),
    ]
