# Generated by Django 5.2.9 on 2026-01-13 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_metamensal_unique_together_metamensal_periodo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metamensal',
            name='tipo',
            field=models.CharField(choices=[('C', 'Por Categoria'), ('K', 'Cartão(ões) de Crédito'), ('E', 'Economia (Guardar)'), ('G', 'Orçamento Global (Teto de Gastos)')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='pago',
            field=models.BooleanField(default=False, verbose_name='Pago?'),
        ),
    ]
