# Generated by Django 5.2.9 on 2026-01-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_metamensal_tipo_alter_transacao_pago'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='metamensal',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='metamensal',
            name='data_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Fim'),
        ),
        migrations.AddField(
            model_name='metamensal',
            name='data_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Início'),
        ),
        migrations.AddField(
            model_name='metamensal',
            name='descricao',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome da Meta (Opcional)'),
        ),
        migrations.AlterField(
            model_name='metamensal',
            name='periodo',
            field=models.CharField(choices=[('M', 'Mensal (Mês Atual)'), ('T', 'Trimestral (Trimestre Atual)'), ('S', 'Semestral (Semestre Atual)'), ('A', 'Anual (Ano Atual)'), ('P', 'Personalizado (Data Específica)')], default='M', max_length=1, verbose_name='Período'),
        ),
    ]
