# Generated by Django 5.2.9 on 2026-01-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_metamensal_unique_together_metamensal_data_fim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metamensal',
            name='descricao',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome da Meta'),
        ),
    ]
