# Generated by Django 5.2.9 on 2025-12-08 00:43

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendenciaReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data_origem', models.DateField(default=datetime.date.today)),
                ('recebido', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiarioMoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=datetime.date.today)),
                ('km_rodado', models.IntegerField(blank=True, null=True)),
                ('ganho_uber', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('ganho_ifood', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('ganho_99', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('ganho_particular', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('gasto_combustivel', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('gasto_manutencao', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('gasto_alimentacao', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'data')},
            },
        ),
    ]
